# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: Auto Validate Quickstarts with devcontainer

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-*
  workflow_dispatch:
jobs:
  deploy:
    name: Validate ${{ matrix.quickstart }}/README.md on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DAPR_CLI_VERSION: 1.2.0
      DAPR_RUNTIME_VERSION: 1.2.0
    strategy:
      matrix:
        quickstart: [hello-world, hello-kubernetes, distributed-calculator, pub-sub, bindings, secretstore, observability, .]
        os: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Start Dev Container
        run: |
          pushd $GITHUB_WORKSPACE/.devcontainer
          docker compose -f docker-compose.yml build --build-arg DAPR_CLI_VERSION=${{ env.DAPR_CLI_VERSION }} quickstarts
          docker compose run -w /workspace --rm quickstarts bash
      - name: Start minikube cluster
        if: matrix.quickstart != '.' && matrix.quickstart != 'hello-world'
        run: |
          minikube start
      - name: Install Dapr
        run: |
          dapr init --runtime-version=${{ env.DAPR_RUNTIME_VERSION }}
          dapr --version
      - name: Install Dapr - Kubernetes
        if: matrix.quickstart != '.' && matrix.quickstart != 'hello-world'
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm install redis bitnami/redis
          dapr init -k --runtime-version=${{ env.DAPR_RUNTIME_VERSION }} --wait
      - name: Validate ${{ matrix.quickstart }}
        run: |
          pushd ${{ matrix.quickstart }}
          make validate
          popd
      - name: Cleanup Dev Container
        run: |
          exit
          docker image rm devcontainer_quickstarts
          docker volume rm devcontainer_codespaces-linux-var-lib-docker
          popd
